export const MAX_LEVEL = 8

export const EASY_SENTENCES = [
  { sentence: 'She ___ happy today.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'They ___ playing football.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'He ___ to school every day.', answer: 'goes', distractors: ['go', 'going', 'went'] },
  { sentence: 'I ___ two brothers.', answer: 'have', distractors: ['has', 'having', 'had'] },
  { sentence: 'The dog ___ under the table.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'We ___ happy to see you.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'This is ___ apple.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'I saw ___ elephant at the zoo.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'There ___ many books on the shelf.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'My sister ___ a doctor.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The cats ___ sleeping now.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'My mother ___ to work by car.', answer: 'goes', distractors: ['go', 'going', 'went'] },
  { sentence: 'He ___ a red car.', answer: 'has', distractors: ['have', 'having', 'had'] },
  { sentence: 'The birds ___ singing in the tree.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'I ___ my homework every day.', answer: 'do', distractors: ['does', 'doing', 'did'] },
  { sentence: 'This is ___ umbrella.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'The children ___ playing outside.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'My brother ___ tall.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'My dog ___ friendly.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The elephant ___ big.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'My friends ___ kind.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'The flowers ___ pretty.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'I ___ excited.', answer: 'am', distractors: ['is', 'are', 'be'] },
  { sentence: 'You ___ funny.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'The soup ___ hot.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'Our teacher ___ patient.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The twins ___ tall.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'My grandma ___ gentle.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The puppies ___ playful.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'This chair ___ broken.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The stars ___ bright.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'My shoes ___ new.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'The movie ___ exciting.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'We ___ ready.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'The baby ___ asleep.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The road ___ long.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'My cousins ___ friendly.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'The garden ___ colorful.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The lake ___ calm.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'Those birds ___ noisy.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'The bread ___ fresh.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'My neighbors ___ nice.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'This puzzle ___ easy.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The kittens ___ small.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'My uncle ___ strong.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The rooms ___ clean.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'This song ___ lovely.', answer: 'is', distractors: ['are', 'am', 'be'] },
  { sentence: 'The children ___ excited.', answer: 'are', distractors: ['is', 'am', 'be'] },
  { sentence: 'She ___ to the market every week.', answer: 'goes', distractors: ['go', 'going', 'went'] },
  { sentence: 'My dad ___ the newspaper every morning.', answer: 'reads', distractors: ['read', 'reading', 'readed'] },
  { sentence: 'The cat ___ on the sofa.', answer: 'sleeps', distractors: ['sleep', 'sleeping', 'slept'] },
  { sentence: 'My friends ___ soccer after school.', answer: 'play', distractors: ['plays', 'playing', 'played'] },
  { sentence: 'He ___ his teeth twice a day.', answer: 'brushes', distractors: ['brush', 'brushing', 'brushed'] },
  { sentence: 'The birds ___ south in winter.', answer: 'fly', distractors: ['flies', 'flying', 'flew'] },
  { sentence: 'My mom ___ dinner every evening.', answer: 'cooks', distractors: ['cook', 'cooking', 'cooked'] },
  { sentence: 'We ___ our homework together.', answer: 'do', distractors: ['does', 'doing', 'did'] },
  { sentence: 'The students ___ their books to class.', answer: 'bring', distractors: ['brings', 'bringing', 'brought'] },
  { sentence: 'She ___ the piano very well.', answer: 'plays', distractors: ['play', 'playing', 'played'] },
  { sentence: 'My brother ___ a bicycle to school.', answer: 'rides', distractors: ['ride', 'riding', 'rode'] },
  { sentence: 'The farmer ___ the fields every day.', answer: 'checks', distractors: ['check', 'checking', 'checked'] },
  { sentence: 'They ___ letters to their grandma.', answer: 'write', distractors: ['writes', 'writing', 'wrote'] },
  { sentence: 'He ___ football on Saturdays.', answer: 'watches', distractors: ['watch', 'watching', 'watched'] },
  { sentence: 'The baby ___ a lot at night.', answer: 'cries', distractors: ['cry', 'crying', 'cried'] },
  { sentence: 'My sister ___ her room every weekend.', answer: 'cleans', distractors: ['clean', 'cleaning', 'cleaned'] },
  { sentence: 'We ___ to school by bus.', answer: 'go', distractors: ['goes', 'going', 'went'] },
  { sentence: 'The dog ___ at strangers.', answer: 'barks', distractors: ['bark', 'barking', 'barked'] },
  { sentence: 'She ___ English and Spanish.', answer: 'speaks', distractors: ['speak', 'speaking', 'spoke'] },
  { sentence: 'My parents ___ me stories at night.', answer: 'tell', distractors: ['tells', 'telling', 'told'] },
  { sentence: 'He ___ the guitar every afternoon.', answer: 'practices', distractors: ['practice', 'practicing', 'practiced'] },
  { sentence: 'The train ___ at nine o\'clock.', answer: 'leaves', distractors: ['leave', 'leaving', 'left'] },
  { sentence: 'My grandpa ___ in the garden.', answer: 'works', distractors: ['work', 'working', 'worked'] },
  { sentence: 'They ___ pizza every Friday.', answer: 'eat', distractors: ['eats', 'eating', 'ate'] },
  { sentence: 'She ___ her homework before dinner.', answer: 'finishes', distractors: ['finish', 'finishing', 'finished'] },
  { sentence: 'The chef ___ delicious food.', answer: 'makes', distractors: ['make', 'making', 'made'] },
  { sentence: 'We ___ the news every night.', answer: 'watch', distractors: ['watches', 'watching', 'watched'] },
  { sentence: 'My friend ___ me every day.', answer: 'calls', distractors: ['call', 'calling', 'called'] },
  { sentence: 'The teacher ___ the class quiz.', answer: 'checks', distractors: ['check', 'checking', 'checked'] },
  { sentence: 'He ___ his room before bed.', answer: 'tidies', distractors: ['tidy', 'tidying', 'tidied'] },
  { sentence: 'This is ___ orange.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'She has ___ umbrella.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'I saw ___ owl in the tree.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'He is ___ engineer.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'That is ___ igloo.', answer: 'an', distractors: ['a', 'the', 'some'] },
  { sentence: 'This is ___ ball.', answer: 'a', distractors: ['an', 'the', 'some'] },
  { sentence: 'She has ___ cat.', answer: 'a', distractors: ['an', 'the', 'some'] },
  { sentence: 'I saw ___ dog in the park.', answer: 'a', distractors: ['an', 'the', 'some'] },
  { sentence: 'He wants ___ banana.', answer: 'a', distractors: ['an', 'the', 'some'] },
  { sentence: 'That is ___ house.', answer: 'a', distractors: ['an', 'the', 'some'] },
  { sentence: 'There ___ a cat on the roof.', answer: 'is', distractors: ['are', 'am', 'was'] },
  { sentence: 'There ___ five apples in the basket.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'There ___ some milk in the fridge.', answer: 'is', distractors: ['are', 'am', 'was'] },
  { sentence: 'There ___ two dogs in the yard.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'There ___ a book on the table.', answer: 'is', distractors: ['are', 'am', 'was'] },
  { sentence: 'There ___ many toys in the box.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'There ___ a spider on the wall.', answer: 'is', distractors: ['are', 'am', 'was'] },
  { sentence: 'There ___ three birds on the branch.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'There ___ a rainbow in the sky.', answer: 'is', distractors: ['are', 'am', 'was'] },
  { sentence: 'There ___ many stars tonight.', answer: 'are', distractors: ['is', 'am', 'was'] },
  { sentence: 'My mom ___ a new necklace.', answer: 'has', distractors: ['have', 'having', 'had'] },
  { sentence: 'I ___ two sisters.', answer: 'have', distractors: ['has', 'having', 'had'] },
  { sentence: 'The house ___ a big garden.', answer: 'has', distractors: ['have', 'having', 'had'] },
  { sentence: 'We ___ a new teacher.', answer: 'have', distractors: ['has', 'having', 'had'] },
  { sentence: 'He ___ a fast bicycle.', answer: 'has', distractors: ['have', 'having', 'had'] },
  { sentence: 'They ___ a small dog.', answer: 'have', distractors: ['has', 'having', 'had'] },
  { sentence: 'She ___ curly hair.', answer: 'has', distractors: ['have', 'having', 'had'] },
  { sentence: 'You ___ a nice smile.', answer: 'have', distractors: ['has', 'having', 'had'] },
  { sentence: 'The bird ___ colorful feathers.', answer: 'has', distractors: ['have', 'having', 'had'] },
  { sentence: 'My friends ___ many books.', answer: 'have', distractors: ['has', 'having', 'had'] },
]

export const HARD_SENTENCES = [
  { sentence: 'Yesterday, I ___ to the park.', answer: 'went', distractors: ['go', 'goes', 'going'] },
  { sentence: 'She is ___ than her brother.', answer: 'taller', distractors: ['tall', 'tallest', 'more tall'] },
  { sentence: 'This cake is ___ than that one.', answer: 'bigger', distractors: ['big', 'biggest', 'more big'] },
  { sentence: 'He ___ his keys yesterday.', answer: 'lost', distractors: ['lose', 'loses', 'losing'] },
  { sentence: 'We ___ to the beach last summer.', answer: 'went', distractors: ['go', 'goes', 'going'] },
  { sentence: 'That is the ___ mountain in the world.', answer: 'tallest', distractors: ['taller', 'tall', 'more tall'] },
  { sentence: 'She ___ her homework yesterday.', answer: 'finished', distractors: ['finish', 'finishes', 'finishing'] },
  { sentence: 'They ___ a movie last night.', answer: 'watched', distractors: ['watch', 'watches', 'watching'] },
  { sentence: 'This puzzle is ___ than I thought.', answer: 'harder', distractors: ['hard', 'hardest', 'more hard'] },
  { sentence: 'My dad ___ dinner every night.', answer: 'cooks', distractors: ['cook', 'cooking', 'cooked'] },
  { sentence: 'I ___ my homework before dinner.', answer: 'did', distractors: ['do', 'does', 'doing'] },
  { sentence: 'The baby ___ all afternoon.', answer: 'slept', distractors: ['sleep', 'sleeps', 'sleeping'] },
  { sentence: 'This book is ___ than that one.', answer: 'thinner', distractors: ['thin', 'thinnest', 'more thin'] },
  { sentence: 'They ___ to the zoo tomorrow.', answer: 'will go', distractors: ['go', 'goes', 'going'] },
  { sentence: 'This is the ___ book I have read.', answer: 'best', distractors: ['better', 'good', 'well'] },
  { sentence: 'My grandmother ___ stories every night.', answer: 'tells', distractors: ['tell', 'telling', 'told'] },
  { sentence: 'The sun ___ in the east.', answer: 'rises', distractors: ['rise', 'rising', 'rose'] },
  { sentence: 'We ___ a big cake for her birthday.', answer: 'made', distractors: ['make', 'makes', 'making'] },
  { sentence: 'Last night, she ___ a letter.', answer: 'wrote', distractors: ['write', 'writes', 'writing'] },
  { sentence: 'He ___ his bike to school yesterday.', answer: 'rode', distractors: ['ride', 'rides', 'riding'] },
  { sentence: 'They ___ home early last night.', answer: 'came', distractors: ['come', 'comes', 'coming'] },
  { sentence: 'I ___ a big fish yesterday.', answer: 'caught', distractors: ['catch', 'catches', 'catching'] },
  { sentence: 'She ___ the answer quickly.', answer: 'knew', distractors: ['know', 'knows', 'knowing'] },
  { sentence: 'We ___ a great time at the party.', answer: 'had', distractors: ['have', 'has', 'having'] },
  { sentence: 'He ___ the ball to his friend.', answer: 'threw', distractors: ['throw', 'throws', 'throwing'] },
  { sentence: 'The teacher ___ us a new song.', answer: 'taught', distractors: ['teach', 'teaches', 'teaching'] },
  { sentence: 'They ___ a sandcastle at the beach.', answer: 'built', distractors: ['build', 'builds', 'building'] },
  { sentence: 'She ___ the door quietly.', answer: 'closed', distractors: ['close', 'closes', 'closing'] },
  { sentence: 'He ___ his lunch at noon.', answer: 'ate', distractors: ['eat', 'eats', 'eating'] },
  { sentence: 'We ___ to the museum last week.', answer: 'went', distractors: ['go', 'goes', 'going'] },
  { sentence: 'The dog ___ the ball back.', answer: 'brought', distractors: ['bring', 'brings', 'bringing'] },
  { sentence: 'She ___ a beautiful picture.', answer: 'drew', distractors: ['draw', 'draws', 'drawing'] },
  { sentence: 'They ___ the race yesterday.', answer: 'won', distractors: ['win', 'wins', 'winning'] },
  { sentence: 'He ___ his hand up in class.', answer: 'raised', distractors: ['raise', 'raises', 'raising'] },
  { sentence: 'I ___ my keys somewhere.', answer: 'left', distractors: ['leave', 'leaves', 'leaving'] },
  { sentence: 'The sun ___ behind the clouds.', answer: 'hid', distractors: ['hide', 'hides', 'hiding'] },
  { sentence: 'She ___ a new song on the radio.', answer: 'heard', distractors: ['hear', 'hears', 'hearing'] },
  { sentence: 'We ___ our tent by the lake.', answer: 'pitched', distractors: ['pitch', 'pitches', 'pitching'] },
  { sentence: 'He ___ the whole cake by himself.', answer: 'finished', distractors: ['finish', 'finishes', 'finishing'] },
  { sentence: 'They ___ the mystery in the end.', answer: 'solved', distractors: ['solve', 'solves', 'solving'] },
  { sentence: 'She ___ a strange noise outside.', answer: 'noticed', distractors: ['notice', 'notices', 'noticing'] },
  { sentence: 'The plane ___ on time.', answer: 'landed', distractors: ['land', 'lands', 'landing'] },
  { sentence: 'This road is ___ than that one.', answer: 'longer', distractors: ['long', 'longest', 'more long'] },
  { sentence: 'My backpack is ___ than yours.', answer: 'heavier', distractors: ['heavy', 'heaviest', 'more heavy'] },
  { sentence: 'She is ___ than her sister.', answer: 'shorter', distractors: ['short', 'shortest', 'more short'] },
  { sentence: 'This test was ___ than the last one.', answer: 'easier', distractors: ['easy', 'easiest', 'more easy'] },
  { sentence: 'The blue whale is the ___ animal on Earth.', answer: 'biggest', distractors: ['bigger', 'big', 'more big'] },
  { sentence: 'He is the ___ runner in the class.', answer: 'fastest', distractors: ['faster', 'fast', 'more fast'] },
  { sentence: 'This soup is ___ than that one.', answer: 'spicier', distractors: ['spicy', 'spiciest', 'more spicy'] },
  { sentence: 'My house is ___ than his.', answer: 'smaller', distractors: ['small', 'smallest', 'more small'] },
  { sentence: 'She is the ___ student in school.', answer: 'smartest', distractors: ['smarter', 'smart', 'more smart'] },
  { sentence: 'This box is ___ than that box.', answer: 'lighter', distractors: ['light', 'lightest', 'more light'] },
  { sentence: 'Winter is ___ than summer.', answer: 'colder', distractors: ['cold', 'coldest', 'more cold'] },
  { sentence: 'This is the ___ day of my life.', answer: 'happiest', distractors: ['happier', 'happy', 'more happy'] },
  { sentence: 'His voice is ___ than mine.', answer: 'louder', distractors: ['loud', 'loudest', 'more loud'] },
  { sentence: 'That mountain is the ___ in the country.', answer: 'highest', distractors: ['higher', 'high', 'more high'] },
  { sentence: 'This river is ___ than that one.', answer: 'deeper', distractors: ['deep', 'deepest', 'more deep'] },
  { sentence: "My grandma's cookies are the ___.", answer: 'tastiest', distractors: ['tastier', 'tasty', 'more tasty'] },
  { sentence: 'The city is ___ than the village.', answer: 'busier', distractors: ['busy', 'busiest', 'more busy'] },
  { sentence: 'This chair is ___ than that stool.', answer: 'more comfortable', distractors: ['comfortable', 'most comfortable', 'comfortabler'] },
  { sentence: 'He is the ___ boy in the family.', answer: 'youngest', distractors: ['younger', 'young', 'more young'] },
  { sentence: 'She is ___ than her brother in math.', answer: 'better', distractors: ['good', 'best', 'well'] },
  { sentence: 'This is the ___ story I have ever heard.', answer: 'funniest', distractors: ['funnier', 'funny', 'more funny'] },
  { sentence: 'That building is the ___ in the city.', answer: 'tallest', distractors: ['taller', 'tall', 'more tall'] },
  { sentence: 'My new phone is ___ than my old one.', answer: 'faster', distractors: ['fast', 'fastest', 'more fast'] },
  { sentence: 'This dress is ___ than that skirt.', answer: 'prettier', distractors: ['pretty', 'prettiest', 'more pretty'] },
  { sentence: 'He is ___ than he looks.', answer: 'stronger', distractors: ['strong', 'strongest', 'more strong'] },
  { sentence: 'Tomorrow, we ___ a picnic.', answer: 'will have', distractors: ['have', 'has', 'having'] },
  { sentence: 'Next week, she ___ her grandma.', answer: 'will visit', distractors: ['visit', 'visits', 'visiting'] },
  { sentence: 'They ___ the project by Friday.', answer: 'will finish', distractors: ['finish', 'finishes', 'finishing'] },
  { sentence: 'I ___ my room this weekend.', answer: 'will clean', distractors: ['clean', 'cleans', 'cleaning'] },
  { sentence: 'He ___ a new bike for his birthday.', answer: 'will get', distractors: ['get', 'gets', 'getting'] },
  { sentence: 'She ___ already eaten her lunch.', answer: 'has', distractors: ['have', 'is', 'was'] },
  { sentence: 'They ___ just arrived at the station.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'I ___ never seen such a big dog.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'He ___ already finished his homework.', answer: 'has', distractors: ['have', 'is', 'was'] },
  { sentence: 'We ___ lived here for five years.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'She ___ visited Paris twice.', answer: 'has', distractors: ['have', 'is', 'was'] },
  { sentence: 'They ___ never tried sushi before.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'He ___ already left the house.', answer: 'has', distractors: ['have', 'is', 'was'] },
  { sentence: 'I ___ just finished my book.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'She ___ already told me the news.', answer: 'has', distractors: ['have', 'is', 'was'] },
  { sentence: 'We ___ already packed our bags.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'They ___ just won the game.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'He ___ never flown on a plane.', answer: 'has', distractors: ['have', 'is', 'was'] },
  { sentence: 'I ___ already done my chores.', answer: 'have', distractors: ['has', 'is', 'was'] },
  { sentence: 'You ___ wear a helmet when you ride a bike.', answer: 'should', distractors: ['shoulds', 'shoulding', 'will'] },
  { sentence: 'She ___ swim very well.', answer: 'can', distractors: ['cans', 'canning', 'could not'] },
  { sentence: 'He ___ finish his homework before playing.', answer: 'must', distractors: ['musts', 'musted', 'musting'] },
  { sentence: 'They ___ be tired after the long trip.', answer: 'must', distractors: ['musts', 'musting', 'musted'] },
  { sentence: 'If it rains, we ___ stay home.', answer: 'will', distractors: ['would', 'are', 'do'] },
  { sentence: 'She ___ speak three languages.', answer: 'can', distractors: ['cans', 'canned', 'canning'] },
  { sentence: 'We ___ not go outside because of the storm.', answer: 'could', distractors: ['can', 'cans', 'canning'] },
  { sentence: 'He ___ finished his meal before he left.', answer: 'had', distractors: ['have', 'has', 'having'] },
  { sentence: 'By the time we arrived, the movie ___ started.', answer: 'had', distractors: ['have', 'has', 'having'] },
  { sentence: 'She ___ never met him before that day.', answer: 'had', distractors: ['have', 'has', 'having'] },
  { sentence: 'I ___ hoped to see you sooner.', answer: 'had', distractors: ['have', 'has', 'having'] },
  { sentence: 'They ___ already left when we called.', answer: 'had', distractors: ['have', 'has', 'having'] },
  { sentence: 'The children ___ finished their lunch when the bell rang.', answer: 'had', distractors: ['have', 'has', 'having'] },
  { sentence: 'This cake tastes ___ than the one I made.', answer: 'sweeter', distractors: ['sweet', 'sweetest', 'more sweet'] },
  { sentence: 'She ___ the violin every day last month.', answer: 'practiced', distractors: ['practice', 'practices', 'practicing'] },
  { sentence: 'Next year, they ___ move to a new house.', answer: 'will', distractors: ['would', 'are', 'do'] },
  { sentence: 'He is the ___ player on the team.', answer: 'best', distractors: ['better', 'good', 'well'] },
]

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

export function makeRound(level) {
  const pool = level >= 5 ? HARD_SENTENCES : EASY_SENTENCES
  const pick = pool[randInt(0, pool.length - 1)]
  const options = [pick.answer, ...pick.distractors].sort(() => Math.random() - 0.5)
  return { sentence: pick.sentence, answer: pick.answer, options }
}
