export const MAX_LEVEL = 6

export const EASY_WORDS = [
  { emoji: '🐶', word: 'Dog' },
  { emoji: '🐱', word: 'Cat' },
  { emoji: '🐮', word: 'Cow' },
  { emoji: '🐷', word: 'Pig' },
  { emoji: '🐴', word: 'Horse' },
  { emoji: '🐑', word: 'Sheep' },
  { emoji: '🐔', word: 'Chicken' },
  { emoji: '🦆', word: 'Duck' },
  { emoji: '🐰', word: 'Rabbit' },
  { emoji: '🐭', word: 'Mouse' },
  { emoji: '🐻', word: 'Bear' },
  { emoji: '🦁', word: 'Lion' },
  { emoji: '🐯', word: 'Tiger' },
  { emoji: '🐵', word: 'Monkey' },
  { emoji: '🐸', word: 'Frog' },
  { emoji: '🐟', word: 'Fish' },
  { emoji: '🐦', word: 'Bird' },
  { emoji: '🐝', word: 'Bee' },
  { emoji: '🐌', word: 'Snail' },
  { emoji: '🐢', word: 'Turtle' },
  { emoji: '🦉', word: 'Owl' },
  { emoji: '🐍', word: 'Snake' },
  { emoji: '🍎', word: 'Apple' },
  { emoji: '🍌', word: 'Banana' },
  { emoji: '🍊', word: 'Orange' },
  { emoji: '🍇', word: 'Grapes' },
  { emoji: '🍉', word: 'Watermelon' },
  { emoji: '🍍', word: 'Pineapple' },
  { emoji: '🍑', word: 'Peach' },
  { emoji: '🍒', word: 'Cherry' },
  { emoji: '🍋', word: 'Lemon' },
  { emoji: '🥕', word: 'Carrot' },
  { emoji: '🌽', word: 'Corn' },
  { emoji: '🥔', word: 'Potato' },
  { emoji: '🍅', word: 'Tomato' },
  { emoji: '🥚', word: 'Egg' },
  { emoji: '🍞', word: 'Bread' },
  { emoji: '🧀', word: 'Cheese' },
  { emoji: '🥛', word: 'Milk' },
  { emoji: '🍰', word: 'Cake' },
  { emoji: '🍪', word: 'Cookie' },
  { emoji: '🍬', word: 'Candy' },
  { emoji: '🍦', word: 'Ice Cream' },
  { emoji: '🍕', word: 'Pizza' },
  { emoji: '🍔', word: 'Hamburger' },
  { emoji: '🌭', word: 'Hot Dog' },
  { emoji: '🍟', word: 'Fries' },
  { emoji: '🍿', word: 'Popcorn' },
  { emoji: '🍩', word: 'Donut' },
  { emoji: '🍫', word: 'Chocolate' },
  { emoji: '🍯', word: 'Honey' },
  { emoji: '⚽', word: 'Ball' },
  { emoji: '📖', word: 'Book' },
  { emoji: '🏠', word: 'House' },
  { emoji: '☀️', word: 'Sun' },
  { emoji: '🌙', word: 'Moon' },
  { emoji: '⭐', word: 'Star' },
  { emoji: '☁️', word: 'Cloud' },
  { emoji: '🎩', word: 'Hat' },
  { emoji: '👟', word: 'Shoe' },
  { emoji: '🧦', word: 'Sock' },
  { emoji: '👕', word: 'Shirt' },
  { emoji: '🥤', word: 'Cup' },
  { emoji: '🪑', word: 'Chair' },
  { emoji: '🚪', word: 'Door' },
  { emoji: '🔑', word: 'Key' },
  { emoji: '⏰', word: 'Clock' },
  { emoji: '👜', word: 'Bag' },
  { emoji: '🥄', word: 'Spoon' },
  { emoji: '🍴', word: 'Fork' },
  { emoji: '🪁', word: 'Kite' },
  { emoji: '🎈', word: 'Balloon' },
  { emoji: '🎁', word: 'Gift' },
  { emoji: '🕯️', word: 'Candle' },
  { emoji: '🔔', word: 'Bell' },
  { emoji: '🥁', word: 'Drum' },
  { emoji: '🚗', word: 'Car' },
  { emoji: '🚌', word: 'Bus' },
  { emoji: '🚂', word: 'Train' },
  { emoji: '⛵', word: 'Boat' },
  { emoji: '✈️', word: 'Airplane' },
  { emoji: '🚀', word: 'Rocket' },
  { emoji: '🌳', word: 'Tree' },
  { emoji: '🌸', word: 'Flower' },
  { emoji: '🍃', word: 'Leaf' },
  { emoji: '🌱', word: 'Plant' },
  { emoji: '🔥', word: 'Fire' },
  { emoji: '💧', word: 'Water' },
  { emoji: '❄️', word: 'Snow' },
  { emoji: '👁️', word: 'Eye' },
  { emoji: '✋', word: 'Hand' },
  { emoji: '🦶', word: 'Foot' },
  { emoji: '👂', word: 'Ear' },
  { emoji: '👃', word: 'Nose' },
  { emoji: '❤️', word: 'Heart' },
  { emoji: '🧊', word: 'Ice' },
  { emoji: '🪀', word: 'Yoyo' },
  { emoji: '🧸', word: 'Teddy' },
  { emoji: '🛏️', word: 'Bed' },
  { emoji: '🪟', word: 'Window' },
  { emoji: '🖊️', word: 'Pen' },
  { emoji: '✏️', word: 'Pencil' },
  { emoji: '🎨', word: 'Paint' },
  { emoji: '🛁', word: 'Bathtub' },
]

export const HARD_WORDS = [
  { emoji: '🐘', word: 'Elephant' },
  { emoji: '☂️', word: 'Umbrella' },
  { emoji: '🦋', word: 'Butterfly' },
  { emoji: '⛰️', word: 'Mountain' },
  { emoji: '🚲', word: 'Bicycle' },
  { emoji: '🍓', word: 'Strawberry' },
  { emoji: '🎸', word: 'Guitar' },
  { emoji: '🌈', word: 'Rainbow' },
  { emoji: '🦕', word: 'Dinosaur' },
  { emoji: '🥪', word: 'Sandwich' },
  { emoji: '🔭', word: 'Telescope' },
  { emoji: '🌋', word: 'Volcano' },
  { emoji: '🐧', word: 'Penguin' },
  { emoji: '🐙', word: 'Octopus' },
  { emoji: '🎒', word: 'Backpack' },
  { emoji: '🛹', word: 'Skateboard' },
  { emoji: '🚁', word: 'Helicopter' },
  { emoji: '🏆', word: 'Trophy' },
  { emoji: '🧭', word: 'Compass' },
  { emoji: '⚓', word: 'Anchor' },
  { emoji: '🌵', word: 'Cactus' },
  { emoji: '⛄', word: 'Snowman' },
  { emoji: '🚒', word: 'Firetruck' },
  { emoji: '🚀', word: 'Spaceship' },
  { emoji: '🦘', word: 'Kangaroo' },
  { emoji: '🐨', word: 'Koala' },
  { emoji: '🦩', word: 'Flamingo' },
  { emoji: '🐫', word: 'Camel' },
  { emoji: '🦙', word: 'Llama' },
  { emoji: '🦔', word: 'Hedgehog' },
  { emoji: '🦇', word: 'Bat' },
  { emoji: '🦈', word: 'Shark' },
  { emoji: '🦭', word: 'Seal' },
  { emoji: '🦥', word: 'Sloth' },
  { emoji: '🦫', word: 'Beaver' },
  { emoji: '🦦', word: 'Otter' },
  { emoji: '🦜', word: 'Parrot' },
  { emoji: '🦢', word: 'Swan' },
  { emoji: '🦃', word: 'Turkey' },
  { emoji: '🐊', word: 'Crocodile' },
  { emoji: '🦎', word: 'Lizard' },
  { emoji: '🦂', word: 'Scorpion' },
  { emoji: '🦚', word: 'Peacock' },
  { emoji: '🪼', word: 'Jellyfish' },
  { emoji: '🔬', word: 'Microscope' },
  { emoji: '🧲', word: 'Magnet' },
  { emoji: '🔋', word: 'Battery' },
  { emoji: '💡', word: 'Lightbulb' },
  { emoji: '✂️', word: 'Scissors' },
  { emoji: '🔨', word: 'Hammer' },
  { emoji: '🔧', word: 'Wrench' },
  { emoji: '🪛', word: 'Screwdriver' },
  { emoji: '🪜', word: 'Ladder' },
  { emoji: '🧰', word: 'Toolbox' },
  { emoji: '🌡️', word: 'Thermometer' },
  { emoji: '💉', word: 'Syringe' },
  { emoji: '🩹', word: 'Bandage' },
  { emoji: '🩺', word: 'Stethoscope' },
  { emoji: '💊', word: 'Pill' },
  { emoji: '🎺', word: 'Trumpet' },
  { emoji: '🎻', word: 'Violin' },
  { emoji: '🎹', word: 'Piano' },
  { emoji: '🎷', word: 'Saxophone' },
  { emoji: '🪗', word: 'Accordion' },
  { emoji: '🏰', word: 'Castle' },
  { emoji: '⛪', word: 'Church' },
  { emoji: '🌉', word: 'Bridge' },
  { emoji: '⛺', word: 'Tent' },
  { emoji: '🏭', word: 'Factory' },
  { emoji: '🏟️', word: 'Stadium' },
  { emoji: '🎡', word: 'Ferris Wheel' },
  { emoji: '🎢', word: 'Roller Coaster' },
  { emoji: '🎠', word: 'Carousel' },
  { emoji: '🛰️', word: 'Satellite' },
  { emoji: '🪐', word: 'Planet' },
  { emoji: '☄️', word: 'Comet' },
  { emoji: '👽', word: 'Alien' },
  { emoji: '🛸', word: 'UFO' },
  { emoji: '🤖', word: 'Robot' },
  { emoji: '⚡', word: 'Lightning' },
  { emoji: '🏜️', word: 'Desert' },
  { emoji: '🏝️', word: 'Island' },
  { emoji: '🍣', word: 'Sushi' },
  { emoji: '🌮', word: 'Taco' },
  { emoji: '🌯', word: 'Burrito' },
  { emoji: '🥐', word: 'Croissant' },
  { emoji: '🥨', word: 'Pretzel' },
  { emoji: '🥯', word: 'Bagel' },
  { emoji: '🥞', word: 'Pancakes' },
  { emoji: '🧇', word: 'Waffle' },
  { emoji: '🍜', word: 'Ramen' },
  { emoji: '🥟', word: 'Dumpling' },
  { emoji: '🍤', word: 'Shrimp' },
  { emoji: '🦞', word: 'Lobster' },
  { emoji: '🥑', word: 'Avocado' },
  { emoji: '🥥', word: 'Coconut' },
  { emoji: '🥭', word: 'Mango' },
  { emoji: '🥝', word: 'Kiwi' },
  { emoji: '🥦', word: 'Broccoli' },
  { emoji: '🍄', word: 'Mushroom' },
  { emoji: '🥜', word: 'Peanuts' },
  { emoji: '🥓', word: 'Bacon' },
  { emoji: '👔', word: 'Necktie' },
  { emoji: '👑', word: 'Crown' },
]

function shuffled(arr) {
  return [...arr].sort(() => Math.random() - 0.5)
}

export function makeRound(level) {
  const pool = level >= 4 ? HARD_WORDS : EASY_WORDS
  const pick = pool[Math.floor(Math.random() * pool.length)]
  const distractors = shuffled(pool.filter((w) => w.word !== pick.word))
    .slice(0, 3)
    .map((w) => w.word)
  return { emoji: pick.emoji, answer: pick.word, options: shuffled([pick.word, ...distractors]) }
}
